runner:
  n_epochs: 100
  total_steps: -1
  gradient_clipping: 5.0
  gradient_accumulate_steps: 4

  log_step: 20000
  save_step: 20000
  max_keep: 100

optimizer:
  name: AdamW_with_schedule
  lr: 2.e-4
  warmup_proportion: 0.07


pretrain_expert:
  datarc:
    num_workers: 16
    train_batch_size: 16
    max_timestep: 0 # Max length for audio feature (0 for no restriction)
    #libri_root: '/NasData/home/junewoo/raw_dataset/speech_recognition/korean_speech_dataset/big_data/ssl/' # If raw libri data is provided, use on-the-fly feature extraction, else use the pre-extracted features under `file_path`
    libri_root: '/home/kaen2891/workspace/ssl_ver2/' # If raw libri data is provided, use on-the-fly feature extraction, else use the pre-extracted features under `file_path`
    file_path: '/home/kaen2891/workspace//data/len_for_bucket/' # Pre-extracted features path. When using on-the-fly feature extraction, this is used to provide length for bucketing.
    sets: ['KoSpeech_1000hour', 'command_sentence_adult'] # can be the subset of ['train-clean-100', 'train-clean-360', 'train-other-500']